### PR TITLE
DM implementation

### PR DESCRIPTION
**Pull request by iamyanbo**
- User can communicate with another user if its a shelter-seeker relationship and only if they have a common application
- the link to the DM page is through /messages/<applicationId>, for example with seeker1, /messages/1 will work.
- when the user sends a message, page will refetch to reflect the changes
image

### CODE REVIEW

**Review by lujorryn — CHANGES_REQUESTED** [review]
Some small nitpicks on the notification dropdown styling from the previous PR:
1. When used on mobile, the notification menu overflows
Screen Shot 2023-12-04 at 9 40 01 PM

2. Would it be possible to increase the height such that the filters, the 2 notifications and the pagination are all visible without scrolling?
Screen Shot 2023-12-04 at 9 40 06 PM

3. Another thing that's "nice to have" but not necessary, when the user toggles the read/unread ascending / descending switch, can we have the pagination go back to 1?
I noticed that it becomes weird if I go to page 3 and toggle to something that doesn't have page 3, it will show nothing
Screen Shot 2023-12-04 at 9 45 34 PM

Other than these the messaging interface looks great!

**Comment by lujorryn** [comment]
Screen Shot 2023-12-04 at 9 54 49 PM

We're getting this on the MessageDetail page again

**Comment by iamyanbo** [comment]
Should all be fixed now. Not sure how exhibit 1 happens but when I tested it works ok? exhibit 2 is adjusted so it will auto fetch messages when you click the icon.

**Review by lujorryn — APPROVED** [review]
All issues previously identified are fixed, thanks for working on this.

**Pull request merged**
